### PR TITLE
Spritesheets and Slice9 implementations

### PR DESCRIPTION
**Pull request by MSGhero**
Spritesheets are now valid sources when looking for assets. E.g.: the `FlxAtlasFrames` output of loading a TexturePacker .png and .json can be registered and used as a source of images.

Added some clip rect changes, but these may need to be changed in Flixel itself instead of just here.

### CODE REVIEW

**Comment by MSGhero** [comment]
Don't merge quite yet, I'm currently adding 9-slice and fixing some style stuff.

**Comment by MSGhero** [comment]
Good 2 go

**Comment by MSGhero** [comment]
@ianharrigan can I get a merge on this?

**Comment by ianharrigan** [comment]
Sorry, i thought i had...

**Pull request merged**
